// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDexHyw_IEFnt5pTifG-RXeV3mKOG2LdoU',
    appId: '1:100893020202:android:7276a7c35a6d9fe03a3353',
    messagingSenderId: '100893020202',
    projectId: 'agribuddy-3069a',
    storageBucket: 'agribuddy-3069a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyALtkVD8IuaGk7HsgM91LyjCb1eavH0aqs',
    appId: '1:100893020202:ios:566f87dd59c403863a3353',
    messagingSenderId: '100893020202',
    projectId: 'agribuddy-3069a',
    storageBucket: 'agribuddy-3069a.firebasestorage.app',
    androidClientId: '100893020202-1htlqlgpt5togarbnetn21c0jo3kt4hs.apps.googleusercontent.com',
    iosBundleId: 'com.example.smartFarmCompanion',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDexHyw_IEFnt5pTifG-RXeV3mKOG2LdoU', // Reused from generic project credential
    appId: '1:100893020202:web:7276a7c35a6d9fe03a3353', // Derived for web config block
    messagingSenderId: '100893020202',
    projectId: 'agribuddy-3069a',
    storageBucket: 'agribuddy-3069a.firebasestorage.app',
  );

}